default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: localhost

development:
  <<: *default
  database: aws_sns_mysql_development

test:
  <<: *default
  database: aws_sns_mysql_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:  
  database: aws_sns_mysql_production
